### ISSUE TITLE
Page title should be `Rock Paper Scissor` not `Odin Project`

### ISSUE THREAD

**Issue by Xenocidy** [Xenocidy/rock-paper-scissors#1]
<img width="268" alt="Screen Shot 2022-10-25 at 10 32 12 PM" src="https://user-images.githubusercontent.com/42292287/197920632-efd54167-4c9b-4aac-9ebe-43056808a722.png">

**Comment by mishhuang** [comment]
Please assign this to me

**Comment by mishhuang** [comment]
Please
