### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Xenocidy** [Xenocidy/rock-paper-scissors#3]
- [ ] Remove `How to run this program` section
- [ ] Add :link: Live Preview(https://xenocidy.github.io/rock-paper-scissors/) in first sentence of the `Rock Paper Scissors` section
- [ ] Add :link: Link to assignment(https://www.theodinproject.com/lessons/foundations-rock-paper-scissors) as last sentence of the `Rock Paper Scissors` section

**Comment by mishhuang** [comment]
Please assign this task to me
